### ISSUE TITLE
Configurable rest client, with `new Trisolar({ ... });`

### ISSUE THREAD

**Issue by jameslendrum** [jameslendrum/trisolar#11]
- [ ] Determine defaults - caching, mocking, auth, promise
- [ ] Should be able to call `new Trisolar()` without options to get the client with default options
- [ ] Pass an options object to further configure the client
  - [ ] Cache on/off, behaviour, #3 
  - [ ] Mocking on/off, behaviour, #6 
  - [ ] Auth on/off, behaviour, #5 
  - [ ] Promise, Observable, or callback, #8 
  - [ ] Additional interceptors, #2
